#
#
version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
            command:
                    - heroku/deploy-via-git:
                            force: true
