#
#
version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
workflows:
  heroku_deploy:
    jobs:
            commands:
                    - heroku/deploy-via-git:
                            force: true
