#
#
jobs:
  deploy:
    executor:
            docker:
                    - https://hub.docker.com/r/cimg/base/tags/edge

    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
