#
#
jobs:
  build:
          docker:
                  - image: r/cimg/base/tags/edge

          steps:
                  - checkout
                  - heroku/install
                  - heroku/deploy-via-git
